services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      secrets:
        - qx_token
        - ADMIN_USER
        - ADMIN_PASS
        - TEST
        - DEVICE
        - SLURM_PROJECT_ID
    container_name: acf-demo-backend
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    #volumes:
      #- .:/app
    ports:
      - "8000:8000"
secrets:
  qx_token:
    external: true
  ADMIN_USER:
    external: true
  ADMIN_PASS:
    external: true
  TEST:
    external: true
  DEVICE:
    external: true
  SLURM_PROJECT_ID:
    external: true